### ISSUE TITLE
Output manifest from Reckoner

### ISSUE THREAD

**Issue by sc7565** [FairwindsOps/reckoner#100]
CLI command to output reckoner courses to output manifest so it can be fed to other CD tools like spinnaker.

https://helm.sh/docs/helm/#helm-template

**Comment by endzyme** [comment]
@sc7565 are envisioning something like `reckoner template ...` or more of a flag on `reckoner plot --template`?

**Comment by sc7565** [comment]
reckoner plot --template 

Concept is to generate the k8s manifest using template flag and store them in s3/gcs and then use in spinnaker  - https://blog.armory.io/deploy-helm-charts-with-spinnaker/ 

We use spinnaker heavily and having a way to generate k8s manifest gives us an upper hand in using reckoner +helm

**Comment by ejether** [comment]
Would `--helm-args` accomplish this with no change?

**Comment by sc7565** [comment]
it should, as long as we can create entire k8s manifest from reckoner plot, we should good..

**Comment by ejether** [comment]
Ah, I'm not sure that is the case or not.

**Comment by sc7565** [comment]
No it will not,

**Comment by endzyme** [comment]
Hi @sc7565 thanks again for the feature request. I am going to try to see what it would take to get this feature in over the next few weeks. I am planning on making a whole different sub-command `reckoner template path/to/course.yml` to try to follow the same helm convention. Helm 3 will be changing the way remote templating works based on [this PR](https://github.com/helm/helm/issues/4527) so this may need some future massaging as we look towards helm 3 support. 

I'll be back with you shortly if that works for you :)

**Comment by sc7565** [comment]
Thanks Nick, will wait for the feature.

**Comment by endzyme** [comment]
Hi @sc7565 - After reviewing the backlog for this project we won't be able to look at this feature until sometime after September. I know that it may be possible to add an additional [`client.go`](https://github.com/reactiveops/reckoner/blob/master/reckoner/helm/client.py#L99-L104) change to the helm client file and maybe support this. I know the settings for `helm template` command are very similar to the `helm upgrade` command, except for things like name of release. 

If, in the mean time between Q4 and now, you wanted to take a stab at adding a `def template()` type function to the client, I'd be happy to take some time to review it.

Thanks again for the feature request and we appreciate your understanding while we clean up some of our backlog features and tech debt.

**Comment by sudermanjr** [comment]
We have added the `reckoner template` command in this PR - https://github.com/FairwindsOps/reckoner/pull/208

A release is forthcoming, but this will be considered done.
