### ISSUE TITLE
Clean Up readme and Usage Documentation

### ISSUE THREAD

**Issue by endzyme** [FairwindsOps/reckoner#117]
The documentation is missing reckoner flags and functionality that would be useful to outline in the Getting Started section. 

Things to document (not exhaustive):
1. `env` var interpolation in settings
2. Nice quality "Getting Started" section with a few examples and workflows
3. Working with different environments / clusters
4. Setting Kubecontext for apply safety
5. Using `--only` flag for `plot`s
6. Behavioral documentation (when a chart or pre_install or post_install hook fails, what happens)
7. Can Reckoner be used in CI/CD capacity? (what's the current user story there)

**Comment by devops2201** [comment]
Thank you very much Nick.

**Comment by endzyme** [comment]
Partly solved with #121

**Comment by endzyme** [comment]
This is mostly solved in v2.1.0+ with a refactor of docs

Still missing
- Env var docs
- Behavioral docs (what happens when hooks fail, etc)
- integration into CI/CD for Reckoner
