### ISSUE TITLE
Using git repository throws `git fetch --tags -v origin` error

### ISSUE THREAD

**Issue by trankchung** [FairwindsOps/reckoner#146]
*Reckoner version*: 2.1.0

*Command*
```
./reckoner plot course.yaml -o vault --dry-run
```

*ERROR*
```
$ ./reckoner plot course.yaml -o vault --dry-run
2019-10-14 19:22:24 my-desktop root[13720] WARNING Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --tags -v origin
2019-10-14 19:22:24 my-desktop root[13720] ERROR Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --tags -v origin
⛵🔥 Encountered unexpected error in Reckoner! Run with --log-level debug to see details! ⛵🔥
```

Tried command below to see log and it throws an error below
```
./reckoner plot --log-level=debug course.yaml -o vault --dry-run --log-level DEBUG  # or debug

Usage: reckoner plot [OPTIONS] COURSE_FILE
Try "reckoner plot --help" for help.

Error: no such option: --log-level
```

*course.yaml*
```
---
namespace: kube-system
repositories:
  stable:
    url: https://kubernetes-charts.storage.googleapis.com
  vault-helm:
    git: https://github.com/hashicorp/vault-helm.git
    path: .  # tried without `path` or path: / but same error
repository: stable

charts:
  vault:
    namespace: vault
    chart: vault
    repository: vault-helm
    version: v0.1.2  # tried SHA but same error
```

**Comment by sudermanjr** [comment]
If the path is the root, then you should leave the path setting out of the config.  This was specified in the log output:

```
2019-10-14 17:54:53  root[86760]  WARNING  Error with path "."! Remove path when chart exists at the repository root
```

**Comment by sudermanjr** [comment]
Also, I'm not sure if specifying git in the top-level repositories works.  Can you try specifying it in the chart spec below? Something like this works for me:

```
namespace: kube-system
repositories:
  stable:
    url: https://kubernetes-charts.storage.googleapis.com
repository: stable

charts:
  vault:
    namespace: vault
    chart: vault
    repository:
      name: vault-helm
      git: https://github.com/hashicorp/vault-helm.git
    version: v0.1.2  # tried SHA but same error




```

**Comment by trankchung** [comment]
@sudermanjr I did both of your suggestions and it's the same error.

1. I removed the path and ran it and same error
1. I changed to use `repository` under the chart and same error

I copied what you have there and it's the same error. I hope it's not git on my system. Do you mind telling me your git version?

**Comment by endzyme** [comment]
I will take a peek at this today - @trankchung sorry for the delay - are you available to chat via IRC or keybase and we can work via chat to connect? You can hit me up at https://keybase.io/nickhuanca or hit me up with a service that might be more convenient. :)

**Comment by trankchung** [comment]
Thanks everyone but I found helmfile that does what I need.

**Comment by endzyme** [comment]
Thanks for your feedback @trankchung
