### ISSUE TITLE
Bad Init error handling

### ISSUE THREAD

**Issue by endzyme** [FairwindsOps/reckoner#149]
Reckoner drops a bad error message if you haven't initialized the helm client locally. It doesn't tell the user any useful information, even in the debug output. 

This issue is to investigate and create a better user experience.

**Comment by sudermanjr** [comment]
My personal opinion is that if helm is not initialized, it should be perfectly safe and convenient to run a `helm init --client` automatically for the user.

**Comment by endzyme** [comment]
Fixed in #140
