### ISSUE TITLE
multiple --helm-args

### ISSUE THREAD

**Issue by OfirHaim1** [FairwindsOps/reckoner#159]
hi, guys,
I want to use in multiple helm args but is felid may I do it the wrong.
$ reckoner --log-level=DEBUG plot ~/xxx-plot-Test.yml --helm-args --set=qcRunDbMigrate=false 
--helm-args --values=traffic-control-topology/values-dt.yaml
this command return:
 helm version --values=traffic-control-topology/values-dt.yaml --short
Encountered errors while reading course file ⛵🔥
Helm Client Failed to initialize: Could not detect helm version

another thing is it possible to add a new -f  path to a new value by command? 

thank you very much for helping

**Comment by sudermanjr** [comment]
@OfirHaim1 Thanks for reaching out.

`--helm-args` is intended to be used for passing arguments to helm that are needed for initialization or more high-level options.

If you are trying to set values in charts, then we strongly recommend setting those in the course.yaml under your chart definition. See the docs here: https://github.com/FairwindsOps/reckoner/tree/master/docs#charts

This all being said, I believe that we need to fix the version check command to not pass these args. I will mark this as a bug and see if we can look into it.
