### ISSUE TITLE
Introduce --all flag and make default behavior run a single heading

### ISSUE THREAD

**Issue by lucasreed** [FairwindsOps/reckoner#186]
Title is fairly self-explanatory, but this is a major change since folks outside of Fairwinds may be using this, and it could cause some disruption. 

Therefore this will be a major version release change methinks.

**Comment by sudermanjr** [comment]
I think it would ease the change if we made it something like this:

```
reckoner plot course.yml
error: --heading or --all are required
```

**Comment by mgoodhart5** [comment]
I think that keeping `-o` as an option (or something that is short like that) instead of having to type `--heading` every time would be nice. It is way faster to type!
