### ISSUE TITLE
`update --dry-run` always shows that and update is needed

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/reckoner#221]
when `--dry-run` is set for `update`  the call to `template` also gets `--dry-run` set and it outputs the full template whereas `get manifest` outputs nothing so it will always see a difference. When `--dry-run` is not set, `update` proceeds as expected.

**Comment by sudermanjr** [comment]
I really don't think we need a `--dry-run` flag on update. Isn't that functionally the same as `diff` ?

**Comment by ejether** [comment]
Yes, basically. 

I'm seeing some potential risk in the way way `debug_args` are handled here though.
