### ISSUE TITLE
environment variables: incorrect syntax passes through to helm without warning

### ISSUE THREAD

**Issue by hopson** [FairwindsOps/reckoner#242]
If template environment variable parsing fails on a value, the unparsed value is returned and only a `DEBUG` message is issued.  This produces unexpected results in the case of a large `values:` block, where there might be multiple environment variables.

I'd suggest it would be preferable to just raise an error and quit for any parsing error.

Example output:
```
2020-10-28 13:30:29 lurch.local root[72484] DEBUG Could not replace Variable daemonset:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  tolerations:
  - operator: Exists
  priorityClassName: fairwinds-critical
rbac.create: 'true'
kubeStateMetrics:
  enabled: 'true'
  resources:
    requests:
      cpu: 250m
      memory: 300Mi
    limits:
      cpu: 300m
      memory: 356Mi
  priorityClassName: fairwinds-critical
kube-state-metrics.rbac.create: 'true'
datadog:
  apiKey: ${DATADOG_API_KEY}
  appKey: ${DATADOG_APP_KEY}
  leaderElection: 'true'
  collectEvents: 'true'
  env:
  - name: KUBE_NODE_HOSTNAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  - name: DD_TAGS
    value: k8s_node_name:$(KUBE_NODE_HOSTNAME)
  - name: DD_LOG_LEVEL
    value: WARN
  - name: DD_LOGS_CONFIG_PROCESSING_RULES
    value: |
      [
        {
          "type": "exclude_at_match", "name": "exclude_healthcheck", "pattern": ".*Request starting.*healthz"},{"type": "exclude_at_match", "name": "exclude_debug", "pattern": ".*DEBUG.*|.*debug.*"
        }
       ]
  resources:
    requests:
      cpu: 100m
      memory: 250Mi
    limits:
      cpu: 200m
      memory: 500Mi
clusterAgent:
  enabled: true
  token: ${RECKONER__DATADOG_CLUSTER_AGENT_TOKEN}
  metricsProvider:
    enabled: true
 with an Env Var: Formatting Error
```

In the above snippet `$(KUBE_NODE_HOSTNAME)` should be `$$(KUBE_NODE_HOSTNAME)` but unless `--log-level debug` is specified there is no feedback, and the string is returned with no substitutions, leaving the values `${DATADOG_API_KEY}` and `{DATADOG_APP_KEY}` unchanged.  The chart is deployed normally (and in this case, `Secret` resources are populated with `${DATADOG_API_KEY}` and `${DATADOG_APP_KEY}`)

https://github.com/FairwindsOps/reckoner/blob/master/reckoner/chart.py#L519 and the same logic is repeated https://github.com/FairwindsOps/reckoner/blob/master/reckoner/chart.py#L603

**Comment by ejether** [comment]
Confirmed this and that it is safely testable with `reckoner template`
