### ISSUE TITLE
Support OCI/ECR Repository Type

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/reckoner#258]
Feature Request. 

AWS and Helm3 support using ECR as a helm chart repository. 
Reckoner could allow transparent use of  OCI ECR repositories

Documentation:
https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_on_EKS.html
https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html
https://helm.sh/docs/topics/registries/#enabling-oci-support

Requires:
export HELM_EXPERIMENTAL_OCI=1

**Comment by HurricanKai** [comment]
Are there docs about this somewhere? Doesn't seem like just putting oci:// as the url works.
