### ISSUE TITLE
reckoner diff doesn't support env vars in toplevel context field

### ISSUE THREAD

**Issue by lucasreed** [FairwindsOps/reckoner#264]
If you set a context like so:
```
context: ${CLUSTER}-aws
```
`reckoner diff` will not fill in the variable contents.

The result is a report that a given chart needs to be installed fresh (It doesn't see that it's installed already).

**Comment by lucasreed** [comment]
Interestingly, all other reckoner commands appear to work ok.

**Comment by ejether** [comment]
That goes here: https://github.com/FairwindsOps/reckoner/blob/d5ce2c7a9149e2d9373b1171a65ffe89cbfde717/reckoner/chart.py#L128

**Comment by ejether** [comment]
I take it back.  That is only for the chart level context. 
Context is tricky and gets passed around and overridden in ways I'm not sure I get right now. 😬 
I think a big hammer could be adding an interpolate env var call hereabouts. https://github.com/FairwindsOps/reckoner/blob/d5ce2c7a9149e2d9373b1171a65ffe89cbfde717/reckoner/chart.py#L250


But a better way would be to look at how contexts are handled and improve that probably.

**Comment by ejether** [comment]
Related: https://github.com/FairwindsOps/reckoner/issues/276
