### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by basilboli** [FairwindsOps/reckoner#475]
Guys, 

What is the good way of transforming existing helm commands into reckoner format yaml ? 
Do you have any automatic converter or complete example using all flags? 

I feel like documentation is not complete and I miss understanding of how to properly use  `--set-string`

Example of helm we have: 
```
   - helm upgrade aaa bbb
      --version vvv
      --kube-context ddd
      --install
      --namespace nnn
      --create-namespace
      --wait
      --timeout 5m0s
      --values foo/bar.yaml
      --set-string myvar=ffff
```

**Comment by lucasreed** [comment]
Hello @basilboli, welcome to reckoner! I think our docs cover the layout of the course file fairly extensively so I'll provide some links here, but let me know if any of it is still unclear.

As for `--set-string` that functionality was removed in pr #266. Ideally all values should be properly parsed as the proper type within the `values` section of your chart release definition in the course file. Let us know if that's not the case. Here's an example of what I mean:

```
values:
  stringVal: "3"
```

The [documentation here](https://reckoner.docs.fairwinds.com/usage/#charts) describes the various keys you can use for a chart. Also please checkout the `import` command (maybe with `reckoner import --help` to see the options available). That is also [documented here](https://reckoner.docs.fairwinds.com/#importing-existing-releases).

A couple notes on some of your arguments:
`--create-namespace`: There is a reckoner CLI arg for this already, but it defaults to true so it will automatically do this for you.

`--wait` and `--timeout` can be passed in using `--helm-args` which is also [documented here](https://reckoner.docs.fairwinds.com/usage/#cli-usage).

**Comment by basilboli** [comment]
Thanks @lucasreed. 
In the meantime I have succeeded to make it work.
As suggestion this block from the documentation in my opinion is confusing: 

```
values:
      set: these
      values:
        - for
        - me
        - please
...
```

Instead of using reserved words `set`, `values` would be better to provide something like 

```
values:
  foo: mysuperapp
  bar:
     baz: 1.0.0


```

**Comment by lucasreed** [comment]
@basilboli I like that suggestion a lot! Would you like to make a PR to update the docs? The relevant file would be here: https://github.com/FairwindsOps/reckoner/blob/master/docs/usage.md

If not, totally fine. I can make a PR but I thought I would ask you first 😄

**Comment by basilboli** [comment]
Sure, no problem. Will do it tomorrow
