### ISSUE TITLE
Document using local helm charts

### ISSUE THREAD

**Issue by basilboli** [FairwindsOps/reckoner#477]
Hi reckoners, 
I have use case when I build custom helm chart on the fly and I want to deploy it directly to kubernetes without publishing it to any helm chart repository. 

It works ok with helm command 
```
helm upgrade foochart path/to/local/chart/baz.tgz
```
where `path/to/local/chart/baz.tgz` is locally built helm chart. 

If we want to do the same with reckoner, the only way I made it work is to publish the chart to the local chart repository and then re-pull it.

I would be glad to contribute if you believe this can be useful and is aligned with the new features roadmap.

**Comment by sudermanjr** [comment]
You can definitely do that currently! 

Looking at the docs, it's not well (or at all) documented currently, so here's an example:

Given the file structure:
```
├── charts
│   └── test-chart
│       ├── Chart.yaml
│       ├── charts
│       ├── templates
│       │   ├── NOTES.txt
│       │   ├── _helpers.tpl
│       │   ├── deployment.yaml
│       │   ├── hpa.yaml
│       │   ├── ingress.yaml
│       │   ├── service.yaml
│       │   ├── serviceaccount.yaml
│       │   └── tests
│       │       └── test-connection.yaml
│       └── values.yaml
└── course.yml
```

This is the course.yml that will deploy that chart.
```
namespace: ns 
charts:
  my-release-name:
    chart: test-chart
    version: ""
    namespace: ns
    repository: ./charts
```

**Comment by sudermanjr** [comment]
I made this issue into a documentation issue, so that we can get it added to the docs. 

Thanks!

**Comment by basilboli** [comment]
Thanks @sudermanjr for the feedback.
