### ISSUE TITLE
Reckoner diff/template could provide a list of api-versions to helm template command

### ISSUE THREAD

**Issue by lucasreed** [FairwindsOps/reckoner#486]
It shouldn't be too difficult to build a list of api-versions from the cluster currently connected (`kubectl api-versions`) and construct a helm template command that includes each of those using the following syntax:

```helm template \
--api-versions v1 \
--api-versions apps/v1 \
...
```

This would be a big value add over the base `helm template` command.

Another caveat to keep in mind is that `reckoner template` can also be run when not connected to a cluster so we need to decide how to handle that. Do we assume a certain version of kubernetes is installed and use it's default versions?

**Comment by sudermanjr** [comment]
Given that a lot of charts are now enabling specifying apiVersions, and given that the trend towards gitops is making the norm, I think we can close this.
