### ISSUE TITLE
Typo in kube.py

### ISSUE THREAD

**Issue by elthariel** [FairwindsOps/reckoner#493]
https://github.com/FairwindsOps/reckoner/blob/20d6a258aeb27895c970a9c752b4cc4e9194c46d/reckoner/kube.py#L116

`annotation_value` should be `label_value` I suppose ?

It results in the following python error:

```
local variable 'annotation_value' referenced before assignment
```

**Comment by lucasreed** [comment]
Thank you for the report @elthariel! This indeed looks like an error. I'll get it fixed shortly.
