### ISSUE TITLE
Detect TILLER_NAMESPACE and Helm version in cluster

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/reckoner#50]
Detecting server-side cluster details would be a nice addition.  Warnings for helm versions and automatically setting tiller-namespace

**Comment by endzyme** [comment]
Can you outline an example use case here? I'm having trouble understanding the problem this solves.

**Comment by sudermanjr** [comment]
If you run reckoner against a cluster where Tiller is in a namespace other than kube-system (the helm default), it simply fails with a message that the Tiller could not be found.  When building other tools that use helm, we have found that looking at the cluster and detecting where the tiller is located can provide more useful feedback to the user, or just automatically set the required config to use the tiller where it is at.

This would require adding the kubernetes client to the codebase though, and may be out of scope for this project.

**Comment by endzyme** [comment]
Thanks for that clarity :) I appreciate it. 

Perhaps as an MVP, this is something that could be a top level tiller-namespace config for the course?

**Comment by sudermanjr** [comment]
Since helm3 renders this unnecessary, I'm going to close it.
