### ISSUE TITLE
allow reckoner to be configured via environment variables

### ISSUE THREAD

**Issue by intrand** [FairwindsOps/reckoner#503]
Cobra is currently used to take in CLI arguments. I think it would be very helpful if `reckoner` picked up an environment variable on my machine that I pre-populate -- say for example `${reckoner_course_file}`.
Currently I just type the variable name each time I want to run `reckoner`. That could be avoided with this proposed enhancement.

I'm unsure if adding more arguments than just the path to the course file makes sense or not. Please evaluate the current Cobra commands and decide if supporting more commands via environment variables seems reasonable.

**Comment by sudermanjr** [comment]
I love this idea. Once the golang version is complete, we should consider adding this.
