### ISSUE TITLE
Feature Request: Multiple cluster support

### ISSUE THREAD

**Issue by mjhuber** [FairwindsOps/reckoner#55]
It would be great to apply a course to multiple clusters at once.  For example, maybe a list of kubectl contexts could be defined and reckoner would apply the file to each of them:

```
namespace: kube-system
repository: stable
contexts:
  - cluster-1
  - cluster-2
  - cluster-3
```

**Comment by sudermanjr** [comment]
This could be an interesting feature, but would we allow different values files or values for each context?  Seems like we could walk down a pretty deep rabbit hole trying to do that.  I suppose there are many charts that don't need different values per cluster.

The issue I see is this, you either have:
- One common course.yml that has the non-unique charts, and one per cluster with the unique charts
OR, if you don't have this feature:
- One course.yml per cluster (which is what we do now)

Could you maybe provide an example of a use-case that you are thinking of for this feature?

**Comment by mjhuber** [comment]
as a start, it would be nice to be able to apply the same course.yml to many clusters.  This could be useful in keeping the same standards across clusters.

say for example i would like to install cert-manager in 3 clusters, and keep them the same version.  Instead of maintaining 3 course.yml files, 1 could be maintained.

more long term, it would be really cool to add template support for values that differ between the clusters.

**Comment by endzyme** [comment]
Taking a pulse here - Would this be a good feature to consider for Q4?
