### ISSUE TITLE
reckoner delete course capability

### ISSUE THREAD

**Issue by jnmoal** [FairwindsOps/reckoner#586]
**Is your feature request related to a problem? Please describe.**
I have some course with a lot of helm chart installed, within various namespaces.
On particular environment, I need to be able to delete everything that have been created with reckoner.

**Describe the solution you'd like**
I'd like a `reckoner delete course.yaml` command with `--run-all` and `-o` option.

**Describe alternatives you've considered**
I actually have a bash script that list all the installed helm charts and their namespace, and delete them, I'd rather let reckoner do it for me.

**Additional context**

**Comment by sudermanjr** [comment]
I have wanted to add this for a long time, and then forget I want it until I need it again :-D
