### ISSUE TITLE
Docker image for Reckoner

### ISSUE THREAD

**Issue by mrpandat** [FairwindsOps/reckoner#640]
Hey 👋 , first of all, thank you for the work on this project, it's very appreciated. 👍 👍 

**Is your feature request related to a problem? Please describe.**
I have to develop my own docker image to run reckoner in my CI/CD pipeline.

**Describe the solution you'd like**
I would like to have an official docker image for reckoner, published on dockerhub.

**Describe alternatives you've considered**
Install Reckoner directly in my helm docker image. 👎 

**Additional context**
How do you deal with this problem yourself ?

I saw that a similar issue was opened [here](https://github.com/FairwindsOps/reckoner/issues/499), but it was closed...

**Comment by mrpandat** [comment]
I made a quick image docker with reckoner inside: https://github.com/mrpandat/reckoner-helm-kubectl

**Comment by intrand** [comment]
Thanks for the suggestion! This is something we offer in many of our other Golang open source projects, but hasn't been a priority for Reckoner. Now that Reckoner has been re-written as Golang, it should be very simple to grab the latest binary from the github release. We're planning on implementing this at some point in the future for similar purposes.

**Comment by mrpandat** [comment]
Is something like https://github.com/mrpandat/docker-reckoner-helm-go/blob/main/Dockerfile would be OK for a pull request inside this repository ? :)

**Comment by intrand** [comment]
> Is something like https://github.com/mrpandat/docker-reckoner-helm-go/blob/main/Dockerfile would be OK for a pull request inside this repository ? :)

We already do OCI images [in](https://github.com/FairwindsOps/goldilocks/blob/master/.goreleaser.yml) [other](https://github.com/FairwindsOps/pluto/blob/master/.goreleaser.yml) [repositories](https://github.com/FairwindsOps/rbac-manager/blob/master/.goreleaser.yml), so we have more or less a standard there (like which base image we're using and how the image gets built). The base image in the linked Dockerfile isn't one that we support, unfortunately. The good news is that I can probably get this request done sooner than later :)

**Comment by reggermont** [comment]
> Now that Reckoner has been re-written as Golang, it should be very simple to grab the latest binary from the github release
The point of Docker images is also to run them in CIs. To use reckoner in a CI, we need a Docker image already built with reckoner.

By the time, I already have mine, but an official one would be great. 



> This is something we offer in many of our other Golang open source projects, but hasn't been a priority for Reckoner.
I can do it for you if you want, but at some point, I'll need someone from your team with Docker Hub and GitHub access to finalize the contribution

**Comment by sudermanjr** [comment]
Docker images should now be published to `us-docker.pkg.dev/fairwinds-ops/oss/reckoner` in the same fashion as our other Golang projects.
