### ISSUE TITLE
v2 course file conversion gets rid of secrets

### ISSUE THREAD

**Issue by Startouf** [FairwindsOps/reckoner#660]
### What happened?

Similar to https://github.com/FairwindsOps/reckoner/issues/654

When doing runtime conversion, it seems like the secrets are kept, but when running reckoner convert -i core.yaml the secret part disappears from the core.yaml file

### What did you expect to happen?

Keep the secrets section

### How can we reproduce this?

Have a secret section and run `running reckoner convert -i core.yaml`

### Version

Version:6+ (Commit:8ed412a47c719c274bb7b19e3a3a9164a56414d3)

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Thanks for the report! Looks like we need to do some work on that conversion function, or at least provide some warnings.
