### ISSUE TITLE
Reckoner not rendering Job annotations

### ISSUE THREAD

**Issue by TheCubicleJockey** [FairwindsOps/reckoner#681]
### What happened?

While using the [Insights agent chart](https://github.com/FairwindsOps/charts/tree/master/stable/insights-agent) feature for [custom annotations for each repo](https://github.com/FairwindsOps/charts/commit/4d6cca17a09c205b96200e9dcd32b1fe08118275). While using `Helm template` with the C[I test values file](https://github.com/FairwindsOps/charts/blob/4d6cca17a09c205b96200e9dcd32b1fe08118275/stable/insights-agent/ci/test-values.yaml), the job annotation for `opa` will show up in the output. However, while using `reckoner template` the job annotation for opa will not show up in the output yaml.

### What did you expect to happen?

While using `reckoner template` or `reckoner apply` I would expect the annotation to show up in the output or apply.

### How can we reproduce this?

Use the above CI test values file to `helm template` and `reckoner template` and there will be a missing the test annotation. 

### Version

reckoner Version:6.0.0, insights chart 2.17.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
Can you please try the latest release candidate of reckoner and the latest Insights chart? This seems unlikely to be a reckoner issue since we simply shell-out to helm. Also, posting an exact course.yaml file that reproduces the issue would be very helpful.
