### ISSUE TITLE
`--log-level` flag is misnamed

### ISSUE THREAD

**Issue by rbren** [FairwindsOps/reckoner#688]
### What happened?

Tried to add `--log-level=DEBUG` per the documentation, but it seems to want `--v`

### What did you expect to happen?

--log-level works

### How can we reproduce this?

add --log-level

### Version

6.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

<img width="520" alt="Screenshot 2024-10-21 at 2 52 43 PM" src="https://github.com/user-attachments/assets/09966f38-0cb8-4de0-a0e4-6e2b6f478654">

**Comment by rbren** [comment]
Hmm seems like it wants an int as well, but the docs say DEBUG should work

```
E1021 18:52:56.049230    1737 root.go:402] invalid argument "DEBUG" for "-v, --v" flag: strconv.ParseInt: parsing "DEBUG": invalid syntax
```

**Comment by sudermanjr** [comment]
Docs need to be updated for Golang version
