### ISSUE TITLE
Multiline output of hooks needs better formatting

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/reckoner#71]
Currently, multiline output on a hook looks like:
```
2019-02-19 14:27:33 root[54531]     INFO Returned stdout: customresourcedefinition.apiextensions.k8s.io/certificates.certmanager.k8s.io unchanged
customresourcedefinition.apiextensions.k8s.io/issuers.certmanager.k8s.io unchanged
customresourcedefinition.apiextensions.k8s.io/clusterissuers.certmanager.k8s.io unchanged
customresourcedefinition.apiextensions.k8s.io/orders.certmanager.k8s.io unchanged
customresourcedefinition.apiextensions.k8s.io/challenges.certmanager.k8s.io unchanged
```

This would be much easier to read if it was indented.  Mostly just a nice-to-have.

**Comment by endzyme** [comment]
I've been thinking about this for a bit now. All the outputs from reckoner aren't 100% necessary the majority of the time. This includes the output from the helm run itself where mostly it's the object states and the chart messages. It may be useful to start cataloging aggregate logs into `.date.recklog` files for stdout and stderr of the scripts that are run. I think debug should still show all the outputs and more but for 80% of our runs (afaik) we could probably survive with less output. 

Another option would be to chop at all `\n` characters and run each newline through the logger (thus putting `YYYY-MM-DD HH:MM:SS user[pid]   LEVL` in front of every output line. This would definite create more logging that would seldom be looked at (if we trust the tool to do the right thing).

**Comment by sudermanjr** [comment]
This is a nice to have and not a blocker for anything.  In addition, it's not a priority for anything right now.  I'm going to close until we have further requests for it.
