### ISSUE TITLE
Feature: Reckoner should check for the namespace before pre_install hooks

### ISSUE THREAD

**Issue by endzyme** [FairwindsOps/reckoner#75]
Generally speaking, if you've got pre_install hooks on a chart definition, you're probably adding or changing something within the configured namespace of the chart. Since the helm command isn't run yet at the time of firing the webhook, we can assume that the namespace may not be there. 

Potential directions to go:
- If namespace doesn't exist, add a flag to be able to autocreate it before pre-install hooks
- If a namespace doesn't exist, fail and don't run the pre-install hooks (skip the chart install)
- If the namespace doesn't exist, just autocreate it (could have un-desireable results or unclear changes)

**Comment by sudermanjr** [comment]
Fixed in #165
