### ISSUE TITLE
Documentation around chart location in git repos is misleading

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/reckoner#81]
https://github.com/reactiveops/reckoner/blob/master/README.md#path
isn't specific enough and is misleading where it describes the 'path' and 'chart path'

Maybe add a small example like this one since the concept doesn't it well in words:
https://github.com/reactiveops/autohelm/blob/master/examples.md#rbac-manager

**Comment by endzyme** [comment]
This has been updated in v2.1.0 - and added to some schema changes - should be in a better place
