### ISSUE TITLE
Feature request "--strict" mode

### ISSUE THREAD

**Issue by willnewby** [FairwindsOps/reckoner#86]
I notice that Reckoner when it fails to install/upgrade a chart, just continues on. I'd really like a strict mode that bails out the whole run and returns an exit code 1 (or something non-zero) if any chart fails. My use case here is a CI/CD flow, since my jobs all pass even if some of the charts fail (which means errors aren't surfaced).

Thanks!

**Comment by endzyme** [comment]
@willnewby I'm picking this up now and I wanted to know if we can do two things.

1. The new behavior is to always exit code != 0 when a chart or hook fails to run, but would still execute all charts in the course definition
1. A new flag of `--exit-on-failure` which exits immediately on any error and does not continue with any other charts in the course definition

If this is acceptable we could also shoot to add a summary of failures and reasons at the end of the run.

**Comment by sudermanjr** [comment]
I would be in favor of defaulting to exit-on-failure and making --continue-on-failure an option, but that would be a larger departure from the existing UX.

**Comment by endzyme** [comment]
I'm down with that too, I'll scope that as the change.

Here's what I've got so far:

- exit code 0 when everything runs successfully
- exit code 1 when either a chart or runhook fail
- immediately exit the app when any failures are encountered 
- add a `--continue-on-error` flag to override the immediate exit behavior

Thanks again everyone for the help identifying the need here.

**Comment by willnewby** [comment]
> I'm down with that too, I'll scope that as the change.
> 
> Here's what I've got so far:
> 
>     * exit code 0 when everything runs successfully
> 
>     * exit code 1 when either a chart or runhook fail
> 
>     * immediately exit the app when any failures are encountered
> 
>     * add a `--continue-on-error` flag to override the immediate exit behavior
> 
> 
> Thanks again everyone for the help identifying the need here.

This sounds rad, and fits the pattern I would expect.
Thanks!

**Comment by endzyme** [comment]
this has been released in `v1.4.0`
